apiVersion: v1
kind: Service
metadata:
  name: kitchen-api
  namespace: kitchen
spec:
  type: NodePort
  selector:
    app: kitchen-api
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30007